CREATE DATABASE IF NOT EXISTS golybrand_new CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE golybrand_new;
CREATE TABLE users (id CHAR(36) PRIMARY KEY, username VARCHAR(30) NOT NULL UNIQUE, full_name VARCHAR(150) NOT NULL, phone VARCHAR(30) NOT NULL, password_hash VARCHAR(255) NOT NULL, sponsor VARCHAR(30) NULL, activated TINYINT(1) NOT NULL DEFAULT 0, mpesa_code VARCHAR(60) NULL, registration_expense DECIMAL(10,2) NOT NULL DEFAULT 1000.00, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, activated_at DATETIME NULL, INDEX(sponsor), CONSTRAINT fk_sponsor FOREIGN KEY(sponsor) REFERENCES users(username) ON UPDATE CASCADE ON DELETE SET NULL);
CREATE TABLE withdrawals (id CHAR(36) PRIMARY KEY, username VARCHAR(30) NOT NULL, phone VARCHAR(30) NOT NULL, amount DECIMAL(10,2) NOT NULL, status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(username), CONSTRAINT fk_withdraw_user FOREIGN KEY(username) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE admins (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE IF NOT EXISTS content_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content_type ENUM('forex','ebook','tiktok','award') NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NULL,
  url VARCHAR(1000) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(content_type), INDEX(active), INDEX(sort_order)
);

CREATE TABLE IF NOT EXISTS trivia_questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question TEXT NOT NULL,
  option_a VARCHAR(500) NOT NULL,
  option_b VARCHAR(500) NOT NULL,
  option_c VARCHAR(500) NOT NULL,
  option_d VARCHAR(500) NOT NULL,
  correct_option ENUM('A','B','C','D') NOT NULL,
  explanation TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(active)
);
