const AAPI='../backend/admin_api.php';let VIEW='pending';
async function aapi(action,payload={}){const r=await fetch(`${AAPI}?action=${action}`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(payload)});const d=await r.json().catch(()=>({success:false,message:'Invalid response'}));if(!r.ok||d.success===false)throw new Error(d.message||'Request failed');return d;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function money(v){return Number(v||0).toLocaleString('en-KE',{minimumFractionDigits:2});}function showMsg(t,type='error'){document.getElementById('loginMsg').innerHTML=`<div class="${type}">${esc(t)}</div>`;}

function showAdminRegister(){document.getElementById('loginForm').classList.add('hidden');document.getElementById('registerForm').classList.remove('hidden');document.getElementById('loginMsg').innerHTML='';}
function showAdminLogin(){document.getElementById('registerForm').classList.add('hidden');document.getElementById('loginForm').classList.remove('hidden');document.getElementById('loginMsg').innerHTML='';}
async function adminRegister(e){e.preventDefault();try{const d=await aapi('register',{username:document.getElementById('regAdminUser').value.trim(),password:document.getElementById('regAdminPass').value,confirm_password:document.getElementById('regAdminConfirm').value,setup_key:document.getElementById('regAdminKey').value});const newUser=document.getElementById('regAdminUser').value.trim();showAdminLogin();document.getElementById('adminUser').value=newUser;showMsg(d.message,'success');}catch(e){showMsg(e.message);}}
async function adminLogin(e){e.preventDefault();try{await aapi('login',{username:document.getElementById('adminUser').value.trim(),password:document.getElementById('adminPass').value});document.getElementById('loginView').classList.add('hidden');document.getElementById('panel').classList.remove('hidden');await loadPending();}catch(e){showMsg(e.message);}}
async function adminLogout(){try{await aapi('logout')}catch(_){}location.reload();}
async function loadStats(){const d=await aapi('stats');document.getElementById('stats').innerHTML=`<div class="stat"><small>Total Users</small><strong>${d.total_users}</strong></div><div class="stat"><small>Active Users</small><strong>${d.active_users}</strong></div><div class="stat"><small>Pending Activations</small><strong>${d.pending_users}</strong></div><div class="stat"><small>Pending Withdrawals</small><strong>${d.pending_withdrawals}</strong></div>`;}
async function loadPending(){VIEW='pending';document.getElementById('title').textContent='Pending Activations';const d=await aapi('pending');document.getElementById('table').innerHTML=d.users.length?`<div class="table-wrap"><table><thead><tr><th>Username</th><th>Full Name</th><th>Phone</th><th>Sponsor</th><th>Payment Ref</th><th>Registered</th><th>Action</th></tr></thead><tbody>${d.users.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.full_name)}</td><td>${esc(u.phone)}</td><td>${esc(u.sponsor||'-')}</td><td><strong>${esc(u.mpesa_code||'-')}</strong></td><td>${esc(u.created_at)}</td><td><button class="action approve" onclick="approve('${esc(u.username)}')">Approve & Activate</button><button class="action reject" onclick="reject('${esc(u.username)}')">Reject</button></td></tr>`).join('')}</tbody></table></div>`:'<p>No pending activations.</p>';await loadStats();}
async function approve(username){if(!confirm(`Activate ${username}?`))return;try{await aapi('approve',{username});await loadPending();}catch(e){alert(e.message);}}
async function reject(username){if(!confirm(`Reject ${username}?`))return;try{await aapi('reject',{username});await loadPending();}catch(e){alert(e.message);}}
async function loadAll(){VIEW='all';document.getElementById('title').textContent='All Users';const d=await aapi('users');document.getElementById('table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Username</th><th>Full Name</th><th>Phone</th><th>Sponsor</th><th>Payment Ref</th><th>Status</th><th>Created</th></tr></thead><tbody>${d.users.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.full_name)}</td><td>${esc(u.phone)}</td><td>${esc(u.sponsor||'-')}</td><td><strong>${esc(u.mpesa_code||'-')}</strong></td><td class="${Number(u.activated)?'active':'pending'}">${Number(u.activated)?'Active':'Pending'}</td><td>${esc(u.created_at)}</td></tr>`).join('')}</tbody></table></div>`;await loadStats();}
async function loadWithdrawals(){VIEW='withdrawals';document.getElementById('title').textContent='Withdrawal Requests';const d=await aapi('withdrawals');document.getElementById('table').innerHTML=d.withdrawals.length?`<div class="table-wrap"><table><thead><tr><th>User</th><th>Phone</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>${d.withdrawals.map(w=>`<tr><td>${esc(w.username)}</td><td>${esc(w.phone)}</td><td>Ksh ${money(w.amount)}</td><td>${esc(w.status)}</td><td>${esc(w.created_at)}</td><td>${w.status==='pending'?`<button class="action approve" onclick="withdrawAction('${esc(w.id)}','approve')">Approve</button><button class="action reject" onclick="withdrawAction('${esc(w.id)}','reject')">Reject</button>`:'-'}</td></tr>`).join('')}</tbody></table></div>`:'<p>No withdrawal requests.</p>';await loadStats();}
async function withdrawAction(id,action){try{await aapi('withdraw_action',{id,action});await loadWithdrawals();}catch(e){alert(e.message);}}
async function refreshCurrent(){if(VIEW==='pending')await loadPending();else if(VIEW==='all')await loadAll();else await loadWithdrawals();}
window.addEventListener('load',async()=>{try{await aapi('session');document.getElementById('loginView').classList.add('hidden');document.getElementById('panel').classList.remove('hidden');await loadPending();}catch(_){}});

let CONTENT_VIEW='trivia';
function showContentManager(){document.getElementById('contentManager').classList.remove('hidden');document.getElementById('title').textContent='Content Manager';loadContent('trivia');}
function hideContentManager(){document.getElementById('contentManager').classList.add('hidden');refreshCurrent();}
function contentLabel(t){return ({trivia:'Trivia Questions',forex:'Forex Classes',ebook:'E-books',tiktok:'TikTok Videos',award:'Best Agent Awards'})[t]||t;}
function showEditor(type,item={}){
 const ed=document.getElementById('contentEditor');
 if(type==='trivia'){
  ed.innerHTML=`<form class="content-form" onsubmit="saveContent(event,'trivia')"><input type="hidden" id="contentId" value="${esc(item.id||0)}"><label>Question</label><textarea id="question" required>${esc(item.question||'')}</textarea><label>Option A</label><input id="option_a" required value="${esc(item.option_a||'')}"><label>Option B</label><input id="option_b" required value="${esc(item.option_b||'')}"><label>Option C</label><input id="option_c" required value="${esc(item.option_c||'')}"><label>Option D</label><input id="option_d" required value="${esc(item.option_d||'')}"><label>Correct Option</label><select id="correct_option"><option value="A" ${item.correct_option==='A'?'selected':''}>A</option><option value="B" ${item.correct_option==='B'?'selected':''}>B</option><option value="C" ${item.correct_option==='C'?'selected':''}>C</option><option value="D" ${item.correct_option==='D'?'selected':''}>D</option></select><label>Explanation (optional)</label><textarea id="explanation">${esc(item.explanation||'')}</textarea><label><input type="checkbox" id="active" ${item.id?((Number(item.active)?'checked':'')):'checked'}> Active</label><button>Save Question</button><button type="button" class="secondary" onclick="showEditor('trivia',{})">Clear</button></form>`;
 }else{
  ed.innerHTML=`<form class="content-form" onsubmit="saveContent(event,'${type}')"><input type="hidden" id="contentId" value="${esc(item.id||0)}"><label>Title</label><input id="titleInput" required value="${esc(item.title||'')}"><label>Description</label><textarea id="description">${esc(item.description||'')}</textarea><label>Link / URL (optional)</label><input id="url" type="url" value="${esc(item.url||'')}" placeholder="https://..."><label>Display Order</label><input id="sortOrder" type="number" value="${esc(item.sort_order||0)}"><label><input type="checkbox" id="active" ${item.id?((Number(item.active)?'checked':'')):'checked'}> Active</label><button>Save Content</button><button type="button" class="secondary" onclick="showEditor('${type}',{})">Clear</button></form>`;
 }
}
async function loadContent(type){CONTENT_VIEW=type;document.getElementById('contentManager').classList.remove('hidden');document.getElementById('contentEditor').innerHTML='';document.getElementById('contentTable').innerHTML='<p>Loading...</p>';try{const d=await aapi('content_list',{type});showEditor(type,{});if(type==='trivia'){document.getElementById('contentTable').innerHTML=d.items.length?`<div class="table-wrap"><table><thead><tr><th>Question</th><th>Answer</th><th>Status</th><th>Action</th></tr></thead><tbody>${d.items.map(x=>`<tr><td>${esc(x.question)}</td><td>${esc(x.correct_option)}</td><td>${Number(x.active)?'Active':'Hidden'}</td><td><button class="action approve" onclick='editContent(${JSON.stringify(x).replace(/'/g,"&#39;")},"trivia")'>Edit</button><button class="action reject" onclick="deleteContent(${x.id},'trivia')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<p>No trivia questions yet.</p>';}else{document.getElementById('contentTable').innerHTML=d.items.length?`<div class="table-wrap"><table><thead><tr><th>Title</th><th>Description</th><th>Link</th><th>Status</th><th>Action</th></tr></thead><tbody>${d.items.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.description||'')}</td><td>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener">Open</a>`:'-'}</td><td>${Number(x.active)?'Active':'Hidden'}</td><td><button class="action approve" onclick='editContent(${JSON.stringify(x).replace(/'/g,"&#39;")},"${type}")'>Edit</button><button class="action reject" onclick="deleteContent(${x.id},'${type}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<p>No content has been added yet.</p>';}}catch(e){document.getElementById('contentTable').innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
function editContent(item,type){showEditor(type,item);window.scrollTo({top:document.getElementById('contentManager').offsetTop,behavior:'smooth'});}
async function saveContent(e,type){e.preventDefault();try{const id=Number(document.getElementById('contentId').value||0);let payload={type,id,active:document.getElementById('active').checked};if(type==='trivia'){payload.question=document.getElementById('question').value;payload.option_a=document.getElementById('option_a').value;payload.option_b=document.getElementById('option_b').value;payload.option_c=document.getElementById('option_c').value;payload.option_d=document.getElementById('option_d').value;payload.correct_option=document.getElementById('correct_option').value;payload.explanation=document.getElementById('explanation').value;}else{payload.title=document.getElementById('titleInput').value;payload.description=document.getElementById('description').value;payload.url=document.getElementById('url').value;payload.sort_order=Number(document.getElementById('sortOrder').value||0);}const d=await aapi('content_save',payload);alert(d.message);await loadContent(type);}catch(e){alert(e.message);}}
async function deleteContent(id,type){if(!confirm('Delete this content?'))return;try{const d=await aapi('content_delete',{id,type});alert(d.message);await loadContent(type);}catch(e){alert(e.message);}}
