services:
  - type: web
    plan: free
    name: golbyrand-agencies
    runtime: docker
    dockerfilePath: ./GOLYBRAND_SYSTEM_NEW/Dockerfile
    envVars:
      - key: ADMIN_REGISTRATION_KEY
        value: GolbyRandAdmin2026!
      - key: DB_HOST
        value: your_mysql_host
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_database_user
      - key: DB_PASS
        value: your_database_password
